[package]
name = "substrate-api-client"
version = "1.0.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = "2018"

[dependencies]
env_logger = "0.6"
ws = "0.7"
hex = "0.3"
log = "0.4"
clap = { version = "2.33", features = ["yaml"] }
serde = "1.0"
regex = "1.1"
serde_json = "1.0"
hex-literal = "0.1"
serde_derive = "1.0"
parity-codec = { version = "3.3", default-features = false }
primitive-types = { version = "0.2", default-features = false, features = ["codec"] }
parity-codec-derive = { version = "3.3", default-features = false }

[dependencies.primitives]
git = 'https://github.com/paritytech/substrate'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'
package = "substrate-primitives"

[dependencies.indices]
git = 'https://github.com/paritytech/substrate'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'
package = "srml-indices"

[dependencies.node-primitives]
git = 'https://github.com/paritytech/substrate'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[dependencies.runtime_io]
git = 'https://github.com/paritytech/substrate'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'
package = "sr-io"

[dependencies.transaction_pool]
git = 'https://github.com/paritytech/substrate'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'
package = "substrate-transaction-pool"

[dependencies.metadata]
git = 'https://github.com/paritytech/substrate'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'
package = "srml-metadata"

[dependencies.balances]
git = 'https://github.com/paritytech/substrate'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'
package = "srml-balances"

[dependencies.keyring]
git = 'https://github.com/paritytech/substrate'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'
package = "substrate-keyring"

[dependencies.system]
git = 'https://github.com/paritytech/substrate'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'
package = "srml-system"

[dependencies.runtime_primitives]
git = 'https://github.com/paritytech/substrate'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'
package = "sr-primitives"

[dev-dependencies.node_runtime]
git = 'https://github.com/paritytech/substrate'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'
package = "node-runtime"

[patch."https://github.com/paritytech/substrate-bip39"]
substrate-bip39 = { path = "substrate-bip39"}

[features]
default = ["std"]
std = [
	"primitives/std",
	"parity-codec/std",
    "runtime_primitives/std",
]

[[example]]
name = "example_get_storage"
path = "src/examples/example_get_storage.rs"

[[example]]
name = "example_transfer"
path = "src/examples/example_transfer.rs"

[[example]]
name = "example_event_callback"
path = "src/examples/example_event_callback.rs"

[[example]]
name = "example_generic_compose_extrinsic"
path = "src/examples/example_generic_compose_extrinsic.rs"