[package]
name = "substrate-api-client"
version = "1.0.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = "2018"

[dependencies]
env_logger = "*"
ws = "*"
hex = "0.3"
log = "*"
rand = "0.6"
clap = { version = "2.33", features = ["yaml"] }
serde = "1.0"
regex = "*"
schnorrkel = "0.1"
tiny-bip39 = "0.6.0"
serde_json = "1.0"
hex-literal = "0.1"
serde_derive = "1.0"
parity-codec = { version = "3.0", default-features = false }
primitive-types = { version = "0.2", default-features = false, features = ["codec"] }
parity-codec-derive = { version = "3.0", default-features = false }

substrate_bip39 = { package="substrate-bip39", 					git = "https://github.com/paritytech/substrate-bip39" }

primitives = 		{ package = "substrate-primitives", 		git = "https://github.com/paritytech/substrate", rev="6e67eff" }
node-primitives = 	{											git = "https://github.com/paritytech/substrate", rev="6e67eff" }
runtime_io = 		{ package = "sr-io", 						git = "https://github.com/paritytech/substrate", rev="6e67eff" }
transaction_pool = 	{ package = "substrate-transaction-pool",	git = "https://github.com/paritytech/substrate", rev="6e67eff" }
metadata = 			{ package = "srml-metadata",				git = "https://github.com/paritytech/substrate", rev="6e67eff" }
balances = 			{ package = "srml-balances",				git = "https://github.com/paritytech/substrate", rev="6e67eff" }
keyring = 			{ package = "substrate-keyring",			git = "https://github.com/paritytech/substrate", rev="6e67eff" }
system = 			{ package = "srml-system", 					git = "https://github.com/paritytech/substrate", rev="6e67eff" }

runtime_primitives = { package = "sr-primitives", 				git = "https://github.com/paritytech/substrate", rev="6e67eff", default-features = false }
inherents = 		 { package = "substrate-inherents", 		git = "https://github.com/paritytech/substrate", rev="6e67eff", default-features = false }

[dev-dependencies]
node-runtime = { 												git = "https://github.com/paritytech/substrate", rev="6e67eff", features = [ "std" ] }

[features]
default = ["std"]
std = [
	"primitives/std",
	"parity-codec/std",
    "runtime_primitives/std",
]

[[example]]
name = "example_get_storage"
path = "src/examples/example_get_storage.rs"

[[example]]
name = "example_transfer"
path = "src/examples/example_transfer.rs"

[[example]]
name = "example_event_callback"
path = "src/examples/example_event_callback.rs"