[package]
name = "test_no_std"
version = "0.1.0"
authors = ["Alain Brenzikofer <alain.brenzikofer@scs.ch>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
libc = { version="0.2", default-features=false }

[dependencies.substrate-api-client] 
package = "substrate-api-client"
path = ".."
default-features=false
features=["full_crypto"]

[dependencies.application-crypto]
git = 'https://github.com/scs/substrate'
branch = "brenzi-fix-full-crypto"
package = "substrate-application-crypto"
default-features = false
features = ["full_crypto"]

[dependencies.sr-io]
git = 'https://github.com/scs/substrate'
branch = "brenzi-fix-full-crypto"
package = 'sr-io'
default-features=false
features = ["disable_oom", "disable_panic_handler"]

#[patch.'https://github.com/paritytech/substrate']
#sr-io = { git = "https://github.com/scs/substraTEE-node", rev = 'd4a057c5841796994b46b6b35de922ec5777fec5' }

#[patch.'https://github.com/scs/substrate-api-client']
#substrate-api-client = { path = "../"}

#[patch.crates-io]
#ed25519-dalek = { git = "https://github.com/scs/ed25519-dalek.git", branch = "no_std_sgx"}
