[package]
name = "api-client-tutorial"
version = "0.1.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = "2018"

[dependencies]
substrate-api-client = { path = "../.." }
codec = { package = "parity-scale-codec", features = ["derive"], version = "1.0.0", default-features = false }

[dependencies.primitives]
git = 'https://github.com/paritytech/substrate'
rev = '6ae3b6c4ddc03d4cdb10bd1d417b95d20f4c1b6e'
package = "substrate-primitives"

[dependencies.keyring]
git = 'https://github.com/paritytech/substrate'
rev = '6ae3b6c4ddc03d4cdb10bd1d417b95d20f4c1b6e'
package = "substrate-keyring"
